version: "3"

services:
  dominion0:
    container_name: localnet-dominion-node-0
    image: dominiond
    build:
      context: $DOMINION_CODE_DIR
      dockerfile: Dockerfile
    ports:
      - "26656-26657:26656-26657"
      - "1317:1317"
      - "9090:9090"
      - "2345:2345"
      - "4500:4500"
    networks:
      localnet:
        ipv4_address: 192.168.10.2

  dominion1:
    container_name: localnet-dominion-node-1
    image: dominiond
    build:
      context: $DOMINION_CODE_DIR
      dockerfile: Dockerfile
    ports:
      - "26666-26667:26656-26657"
      - "1318:1317"
      - "9091:9090"
      - "2346:2345"
      - "4501:4500"
    networks:
      localnet:
        ipv4_address: 192.168.10.3
    environment:
      - PRIMARY_NODE_ADDR=localnet-dominion-node-0
    entrypoint:
      - /bin/bash
      - -c
      - |
        echo 'Waiting for primary node to come up.'
        until [ \
        "$$(curl -s -w '%{http_code}' -o /dev/null "http://$${PRIMARY_NODE_ADDR}:1317/node_info")" \
        -eq 200 ]
        do
          echo '.'
          sleep 2
        done
        echo 'Primary node is up.'
        export PRIMARY_NODE_ID=$$(curl --retry 3 --retry-delay 5 -X GET "http://$${PRIMARY_NODE_ADDR}:1317/node_info" -H "accept: application/json" \
        | dasel -r json ".node_info.id" | tr -d '"')
        curl "http://$${PRIMARY_NODE_ADDR}:26657/genesis" | dasel -r json .result.genesis > ~/.dominion/config/genesis.json
        dasel put -t string -f ~/.dominion/config/config.toml -s p2p.persistent_peers -v "$${PRIMARY_NODE_ID}@$${PRIMARY_NODE_ADDR}:26656"
        dominiond start

networks:
  localnet:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.10.0/25
